CREATE TABLE blue_items (
    supplier_part_no VARCHAR(120),
    clean_sup_part_no VARCHAR(120),
    supplier_id VARCHAR(120),
    item_prefix VARCHAR(120),
    item_id VARCHAR(120),
    clean_item VARCHAR(120),
    product_type VARCHAR(120),
    on_price_book_flag VARCHAR(120),
    cln_location_cnt VARCHAR(120),
    no_of_suppliers VARCHAR(120),
    no_of_locations VARCHAR(120),
    buyable_locs VARCHAR(120),
    sellable_locs VARCHAR(120),
    delete_locs VARCHAR(120),
    discontinued_locs VARCHAR(120),
    prod_groups VARCHAR(120),
    prod_grps VARCHAR(120),
    sales_disc_grp VARCHAR(120),
    sales_disc_grps VARCHAR(120),
    purch_disc_grp VARCHAR(120),
    purch_disc_grps VARCHAR(120),
    std_cost_updates VARCHAR(120),
    std_cost_update_amt VARCHAR(120),
    discrepancy_type VARCHAR(120)
);